### ISSUE TITLE
Hyde.dll

### ISSUE THREAD

**Issue by sinfulken1** [Lew29/The-Finals-Anti-Recoil#1]
Please make it so that its just the AHK without hyde. No reason why we need hyde to run an ahk script.

**Comment by Lew29** [comment]
> Please make it so that its just the AHK without hyde. No reason why we need hyde to run an ahk script.

It's there to hide the script and make it less detectable by the anti-cheat. 
It is taken from [mgsweets apex anti-recoil script](https://github.com/mgsweet/Apex-NoRecoil-2021) which has thousands of downloads and [here's](https://www.autohotkey.com/board/topic/78872-hyde-your-process-from-the-task-manager/) the earliest mention I can find of it from a 2012 AHK thread.

Nevertheless, if you prefer not to use it, I've provided a version below without the files. Keep in mind that this might increase the likelihood of detection:
[The-Finals-Anti-Recoil-NoHider.zip](https://github.com/Lew29/The-Finals-Anti-Recoil/files/13788181/The-Finals-Anti-Recoil-NoHider.zip)

**Comment by Gerbeev** [comment]
Hi Lew, the code that you've provided (w/o hyde.dll) is not compiling due to errors. Could you please review it?
upd. or maybe this is my mistake, I'm using v2 compiler instead of v1

**Comment by Lew29** [comment]
> Hi Lew, the code that you've provided (w/o hyde.dll) is not compiling due to errors. Could you please review it?

My bad. I deleted too many lines and didn't bother testing it.

I've updated the link, that version should work now.

> or maybe this is my mistake, I'm using v2 compiler instead of v1

No this was my fault.

**Comment by Gerbeev** [comment]
Hey, here is the fixed version without Hide.dll library, compiled by v1 compiler:
[The-Finals-Anti-Recoil.zip](https://github.com/Lew29/The-Finals-Anti-Recoil/files/13788549/The-Finals-Anti-Recoil.zip)
