### ISSUE TITLE
End command not working?

### ISSUE THREAD

**Issue by GAMERGOD2636** [Lew29/The-Finals-Anti-Recoil#9]
I can't seem to get the end command to work.

**Comment by Lew29** [comment]
It's not a necessary and you can just close the script in the system tray. The end key works fine for me but if yours is broken you can just change this on line 185 in run me:
`~$*End::`

[Here](https://www.autohotkey.com/docs/v1/KeyList.htm) is a list of the names for buttons on the keyboard in ahk and changing it to delete would look like this:
`~$*Del::`

**Comment by KOSOVALI12** [comment]
@Lew29  Is it possible for me to contact you privately, I would like to ask you a question on a different subject.

**Comment by Lew29** [comment]
> @Lew29 Is it possible for me to contact you privately, I would like to ask you a question on a different subject.

Sure my discord is lew5

**Comment by KOSOVALI12** [comment]
IM WRİST
